### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Rowbotronics** [MakeICT/electronic-door#55]
The server crashes occasionally. 

Not sure if all the crashes have the same cause, this is the first log file I got that caught it.

 [log_02-01-17.txt](https://github.com/MakeICT/electronic-door/files/815548/log_02-01-17.txt)

> Mar 02 18:58:01 mcp node[19001]: Super serial reconnecting
Mar 02 18:58:01 mcp node[19001]: Super Serial disabled
Mar 02 18:58:01 mcp node[19001]: message Super Serial disconnected  ,
Mar 02 18:58:01 mcp node[19001]: buffer.js:201
Mar 02 18:58:01 mcp node[19001]: length += list[i].length;
Mar 02 18:58:01 mcp node[19001]: ^
Mar 02 18:58:01 mcp node[19001]: TypeError: Cannot read property 'length' of undefined
Mar 02 18:58:01 mcp node[19001]: at Function.Buffer.concat (buffer.js:201:24)
Mar 02 18:58:01 mcp node[19001]: at SerialPort.<anonymous> (/home/pi/code/electronic-door/server/software/plugins/mcp-plugin-super-serial/node_modules/serialport/lib/serialport.js:287:32)
Mar 02 18:58:01 mcp node[19001]: at SerialPort.<anonymous> (/home/pi/code/electronic-door/server/software/plugins/mcp-plugin-super-serial/node_modules/serialport/lib/serialport.js:303:7)
Mar 02 18:58:01 mcp node[19001]: at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)
Mar 02 18:58:01 mcp systemd[1]: master-control-program.service: main process exited, code=exited, status=1/FAILURE
Mar 02 18:58:01 mcp systemd[1]: Unit master-control-program.service entered failed state.
Mar 02 18:58:01 mcp systemd[1]: master-control-program.service holdoff time over, scheduling restart.
Mar 02 18:58:01 mcp systemd[1]: Stopping Master Control Program...
Mar 02 18:58:01 mcp systemd[1]: Starting Master Control Program...
Mar 02 18:58:01 mcp systemd[1]: Started Master Control Program.

**Comment by Rowbotronics** [comment]
> Apr 18 13:24:00 mcp node[396]: Writing packet : fa0700ff042020202052656420627574746f6e2020202061726d732074686520616c61726d205909fb
Apr 18 13:24:00 mcp node[396]: RAW Serial     : fa,7,0,ff,4,20,20,20
Apr 18 13:24:00 mcp node[396]: RAW Serial     : 20,52,65,64,20,62,75,74
Apr 18 13:24:00 mcp node[396]: RAW Serial     : 74,6f,6e,20,20,20,20,61
Apr 18 13:24:00 mcp node[396]: RAW Serial     : 72,6d,73,20,74,68,65,20
Apr 18 13:24:00 mcp node[396]: RAW Serial     : 61,6c,61,72,6d,20,59,9
Apr 18 13:24:00 mcp node[396]: RAW Serial     : fb
Apr 18 13:24:00 mcp node[396]: Incoming packet: fa0700ff042020202052656420627574746f6e2020202061726d732074686520616c61726d205909fb
Apr 18 13:24:00 mcp node[396]: RAW Serial     : fa,b4,3,0,e,0,3e,90
Apr 18 13:24:00 mcp node[396]: error Super serial watchdog activated  ,
Apr 18 13:24:00 mcp node[396]: RAW Serial     : fb
Apr 18 13:24:00 mcp node[396]: Incoming packet: fab403000e003e90fb
Apr 18 13:24:00 mcp node[396]: =============================
Apr 18 13:24:00 mcp node[396]: Received : 250,180,3,0,14,0,62,144,251
Apr 18 13:24:01 mcp node[396]: Unescaped : 250,180,3,0,14,0,62,144,251
Apr 18 13:24:01 mcp node[396]: ID : 180
Apr 18 13:24:01 mcp node[396]: From : 3
Apr 18 13:24:01 mcp node[396]: To : 0
Apr 18 13:24:01 mcp node[396]: Command : 14
Apr 18 13:24:01 mcp node[396]: Payload :
Apr 18 13:24:01 mcp node[396]: =============================
Apr 18 13:24:01 mcp node[396]: Sending ACK for 180 to 3
Apr 18 13:24:01 mcp node[396]: Writing packet : fab40003aa00ba1afb
Apr 18 13:24:01 mcp node[396]: Super serial reconnecting
Apr 18 13:24:01 mcp node[396]: Super Serial disabled
Apr 18 13:24:01 mcp node[396]: message Super Serial disconnected  ,
Apr 18 13:24:01 mcp node[396]: buffer.js:201
Apr 18 13:24:01 mcp node[396]: length += list[i].length;
Apr 18 13:24:01 mcp node[396]: ^
Apr 18 13:24:01 mcp node[396]: TypeError: Cannot read property 'length' of undefined
Apr 18 13:24:01 mcp node[396]: at Function.Buffer.concat (buffer.js:201:24)
Apr 18 13:24:01 mcp node[396]: at SerialPort.<anonymous> (/home/pi/code/electronic-door/server/software/plugins/mcp-plugin-super-serial/node_modules/serialport/lib/serialport.js:287:32)
Apr 18 13:24:01 mcp node[396]: at SerialPort.<anonymous> (/home/pi/code/electronic-door/server/software/plugins/mcp-plugin-super-serial/node_modules/serialport/lib/serialport.js:303:7)
Apr 18 13:24:01 mcp node[396]: at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)
Apr 18 13:24:01 mcp systemd[1]: master-control-program.service: main process exited, code=exited, status=1/FAILURE
Apr 18 13:24:01 mcp systemd[1]: Unit master-control-program.service entered failed state.
Apr 18 13:24:01 mcp systemd[1]: master-control-program.service holdoff time over, scheduling restart.
Apr 18 13:24:01 mcp systemd[1]: Stopping Master Control Program...
Apr 18 13:24:01 mcp systemd[1]: Starting Master Control Program...
Apr 18 13:24:01 mcp systemd[1]: Started Master Control Program.

**Comment by 0x7EVEN** [comment]
I can fix this will you assign this to me
